### ISSUE TITLE
unexpected EOF during apply

### ISSUE THREAD

**Issue by drewyelle** [DimensionDataResearch/terraform-provider-ddcloud#108]
Taking The first stab at deploying to DimensionData/MedOne Cloud in Israel (datacenter IL1). Using a local copy of the basic example "Testing the Provider" project located here: https://github.com/DimensionDataResearch/dd-cloud-compute-terraform

Terraform plan is successful. Terraform apply fails with an EOF error. 

**Expected behavior:**
Terraform apply is successful.
Plan: 5 to add, 0 to change, 0 to destroy.

**Observed behavior:**

PS C:\Tools\GITLAB\terraform\medone> terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + ddcloud_firewall_rule.my-vm-http-in
      id:                             <computed>
      action:                         "ACCEPT_DECISIVELY"
      destination_address:            "${ddcloud_nat.my-server-nat.public_ipv4}"
      destination_port:               "80"
      enabled:                        "true"
      ip_version:                     "ipv4"
      name:                           "my_server.HTTP.Inbound"
      networkdomain:                  "${ddcloud_networkdomain.my-domain.id}"
      placement:                      "first"
      protocol:                       "tcp"

  + ddcloud_nat.my-server-nat
      id:                             <computed>
      networkdomain:                  "${ddcloud_networkdomain.my-domain.id}"
      private_ipv4:                   "${ddcloud_server.my-server.primary_adapter_ip
      public_ipv4:                    <computed>

  + ddcloud_networkdomain.my-domain
      id:                             <computed>
      datacenter:                     "IL1"
      description:                    "This is my Terraform test network domain."
      name:                           "terraform-test-domain"
      nat_ipv4_address:               <computed>
      outside_transit_ipv4_subnet:    <computed>
      plan:                           "ADVANCED"

  + ddcloud_server.my-server
      id:                             <computed>
      additional_network_adapter.#:   <computed>
      admin_password:                 <sensitive>
      auto_start:                     "false"
      backup_client_urls.%:           <computed>
      backup_enabled:                 <computed>
      cores_per_cpu:                  <computed>
      cpu_count:                      "2"
      cpu_speed:                      <computed>
      description:                    "This is my Terraform test server."
      disk.#:                         "2"
      disk.0.id:                      <computed>
      disk.0.scsi_bus_number:         <computed>
      disk.0.scsi_unit_id:            "0"
      disk.0.size_gb:                 "10"
      disk.0.speed:                   "STANDARD"
      disk.1.id:                      <computed>
      disk.1.scsi_bus_number:         <computed>
      disk.1.scsi_unit_id:            "1"
      disk.1.size_gb:                 "20"
      disk.1.speed:                   "STANDARD"
      dns_primary:                    "8.8.8.8"
      dns_secondary:                  "8.8.4.4"
      image:                          "CentOS 7 64-bit 2 CPU"
      image_type:                     "auto"
      memory_gb:                      "4"
      name:                           "terraform-server"
      networkdomain:                  "${ddcloud_networkdomain.my-domain.id}"
      os_family:                      <computed>
      os_type:                        <computed>
      power_state:                    "disabled"
      primary_adapter_ipv4:           <computed>
      primary_adapter_ipv6:           <computed>
      primary_adapter_type:           <computed>
      primary_adapter_vlan:           <computed>
      primary_network_adapter.#:      "1"
      primary_network_adapter.0.id:   <computed>
      primary_network_adapter.0.ipv4: "10.100.17.10"
      primary_network_adapter.0.ipv6: <computed>
      primary_network_adapter.0.mac:  <computed>
      primary_network_adapter.0.type: <computed>
      primary_network_adapter.0.vlan: <computed>
      public_ipv4:                    <computed>
      started:                        <computed>

  + ddcloud_vlan.my-vlan
      id:                             <computed>
      description:                    "Terraform test VLAN"
      ipv4_base_address:              "10.100.17.0"
      ipv4_prefix_size:               "24"
      ipv6_base_address:              <computed>
      ipv6_prefix_size:               <computed>
      name:                           "terraform-test-vlan"
      networkdomain:                  "${ddcloud_networkdomain.my-domain.id}"

Plan: 5 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

ddcloud_networkdomain.my-domain: Creating...
  datacenter:                  "" => "IL1"
  description:                 "" => "This is my Terraform test network domain."
  name:                        "" => "terraform-test-domain"
  nat_ipv4_address:            "" => "<computed>"
  outside_transit_ipv4_subnet: "" => "<computed>"
  plan:                        "" => "ADVANCED"

Error: Error applying plan:

1 error(s) occurred:

* ddcloud_networkdomain.my-domain: 1 error(s) occurred:

* ddcloud_networkdomain.my-domain: EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

OS: Windows7, SP1
> terraform providers --version
Terraform v0.11.3
+ provider.ddcloud (unversioned)

>terraform-provider-ddcloud --version
terraform-provider-ddcloud.exe v1.3.3-preview1 (6b56ef5c9258555cecbd7a164b4372c0fc824039)

**Comment by tintoy** [comment]
Hi - would you be able to set the following environment variables and run the command again?

```
set TF_LOG=DEBUG
set TF_LOG_PATH=.\apply.log
set MCP_EXTENDED_LOGGING=1
```

If you could then attach the resulting log file it may help to throw some light on the problem.

**Comment by calloes** [comment]
Are you able to show your terraform.tf file please ensure you pull and variables out.

Chris

**Comment by drewyelle** [comment]
Thanks tintoy for the quick response. 

I have found the error. The URL built in the initial GET was incorrect. The path was malformed and led to a 404 response. When specifying the **datacenter** value in the **ddcloud_networkdomain** resource, there should not be any URI path specified but the "https://" prefix is required. 

Incorrect: 
datacenter     =   "https://api.cloud.med-1.com/oec/0.9/"
Correct: 
datacenter     =   "https://api.cloud.med-1.com"
