### ISSUE TITLE
Enhace virtual listener documentation

### ISSUE THREAD

**Issue by adrianriobo** [DimensionDataResearch/terraform-provider-ddcloud#109]
According with [virtual listener public ip](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/issues/19)

Virtual listener should have ipv4 as referenced attribute, so it is possible to get assigned public ip to create a firewall rule from this... (nat style).

**Comment by tintoy** [comment]
Hi - thanks, I'll have a look at this first thing on Monday.

**Comment by tintoy** [comment]
Hi - I've updated the documentation to list `ipv4` as a computed attribute.

Thanks :)
