### ISSUE TITLE
ssl_offload_profile not set from virtuallistener

### ISSUE THREAD

**Issue by adrianriobo** [DimensionDataResearch/terraform-provider-ddcloud#110]
Terraform v0.11.3
terraform-provider-ddcloud v1.3.3-preview1 (6b56ef5c9258555cecbd7a164b4372c0fc824039)

Creating a virtual listener with an ssl offload profile from terraform output...

```
module.ssloffload_profile.ddcloud_ssl_offload_profile.default: Creating...
  certificate:   "" => "94f2255f-99e0-4f5c-91b0-40255e10ca7a"
  ciphers:       "" => "<computed>"
  name:          "" => "ssloffload"
  networkdomain: "" => "4a3a032c-d62e-4d41-a122-37150827c98a"

module.ssloffload_profile.ddcloud_ssl_offload_profile.default: Creation complete after 13s (ID: 31122c43-796f-4e52-b5be-dad67a5487bc)

module.vip.ddcloud_virtual_listener.default: Creating...
  connection_limit:                "" => "20000"
  connection_rate_limit:           "" => "2000"
  enabled:                         "" => "true"
  ipv4:                            "" => "<computed>"
  name:                            "" => "virtuallistener_sophie"
  networkdomain:                   "" => "4a3a032c-d62e-4d41-a122-37150827c98a"
  optimization_profiles.#:         "" => "1"
  optimization_profiles.617288268: "" => "TCP"
  persistence_profile:             "" => "CCDEFAULT.Cookie"
  pool:                            "" => "126d9a38-d513-4ca6-8b55-49eee926ee45"
  port:                            "" => "0"
  protocol:                        "" => "HTTP"
  source_port_preservation:        "" => "PRESERVE"
  ssl_offload_profile:             "" => "31122c43-796f-4e52-b5be-dad67a5487bc"
  type:                            "" => "STANDARD"

module.vip.ddcloud_virtual_listener.default: Creation complete after 4s (ID: 0da86d60-dae4-4696-ba3c-72da1e6e9e2e)

```
But if I go to console and check the virtual listener, ssl offload profile is not set:

![ssloffloadprofileerror](https://user-images.githubusercontent.com/1957899/37390555-c9a9da10-2768-11e8-9020-fda041e4ea50.PNG)

**Comment by tintoy** [comment]
Hmm, sorry, that does sound like a bug. I'll try it with logging and see what's going on.

**Comment by adrianriobo** [comment]
Ok, curious, all my resources are created perfect this is the only thing is not proper set...the profile is created and if I use combo I can select the ssl offfload profile

...the only thing I am not doing as doc from MCP says is .. (but there is no complaint about)

I am setting PersistenceProfile CCDEFAULT.Cookie...which from documentation it says it is not possible with Standard virtual listener... but I checked from console and it seems it is possible...

I don´t know if maybe has something to do with this...

**Comment by tintoy** [comment]
It's around 10pm here in AU but I'll look into this properly tomorrow morning. In the meanwhile could you try defining the following environment variables and the  capture the output from terraform apply? TF_LOG=DEBUG MCP_EXTENDED_LOGGING=1

**Comment by adrianriobo** [comment]
yes no problem, I will make it this afternoon so you will have it tomorrow morning (AU) :)

Thx

**Comment by adrianriobo** [comment]
Hi there, here you have (attached) debug log for virtual listener resource, I just paste the part of the virtual listener because full stack seems irrelevant...

[virtuallistener.log](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/files/1812272/virtuallistener.log)

Some points I saw in this log:

1. When virtual listener attributes are printed no ssl offload profile info is printed. Maybe previously it was not, and during ssl offload attribute support development no debug information was added

2. Some virtual listener validation against persistent profiles is checked..and it says:
[{"name":"CCDEFAULT.Cookie","virtualListenerCompatibility":[{"type":"STANDARD","protocol":"HTTP"}
which is not represented in [MCP 2.0 persistent profile info](https://docs.mcp-services.net/display/CCD/Introduction+to+Persistence+Profiles+at+an+MCP+2.0+Data+Center)

3. Request body for create virtual listener **post request contains ssloffloadprofile:**

`Request body: '{"name":"virtuallistener_sophie","description":"","type":"STANDARD","protocol":"HTTP","enabled":true,"connectionLimit":20000,"connectionRateLimit":2000,"sourcePortPreservation":"PRESERVE","poolId":"d65fe972-e064-40c9-b00b-279b16a7ac5a","persistenceProfileId":"a3a89464-1b6d-11e5-8d4f-180373fb68df","sslOffloadProfileId":"a0bbf629-d9a5-49e8-90a1-a3efdb8208e0","iruleId":[],"optimizationProfile":["TCP"],"networkDomainId":"0dbcf467-73a3-48bc-8100-98d78547ec88"}'`

And it returns code 200...

4. When get request is executed to get virtual listener resource information...**response does not include ssloffloadprofile**:

`'{"networkDomainId":"0dbcf467-73a3-48bc-8100-98d78547ec88","name":"virtuallistener_sophie","state":"NORMAL","description":"","createTime":"2018-03-14T16:37:11.000Z","type":"STANDARD","protocol":"HTTP","listenerIpAddress":"168.128.13.160","enabled":true,"connectionLimit":20000,"connectionRateLimit":2000,"sourcePortPreservation":"PRESERVE","pool":{"loadBalanceMethod":"ROUND_ROBIN","serviceDownAction":"NONE","slowRampTime":5,"id":"d65fe972-e064-40c9-b00b-279b16a7ac5a","name":"pool_sophie"},"persistenceProfile":{"id":"a3a89464-1b6d-11e5-8d4f-180373fb68df","name":"CCDEFAULT.Cookie"},"optimizationProfile":["TCP"],"irule":[],"id":"8c1dad4a-998a-46a5-a342-9f8a66e9ea7d","datacenterId":"EU6"}'`

So, it seems if there was any problem with the association, post request for virtual listener should not return code 200, if it does 200 it is supposed post request should set everything fine no?

**Comment by tintoy** [comment]
Hmm, looks like GitHub is having trouble with file storage at the moment; I can't download the log file for some reason.

Looking at the CloudControl API documentation for `sslOffloadProfileId`, it looks to me like you've got a valid configuration so I'm not sure why it's not taking.

> An sslOffloadProfileId can only be included for certain type, protocol and optimizationProfile combinations:
>  * type must be STANDARD.
>  * protocol must be one of the following: TCP, HTTP, FTP, or SMTP.
>  * optimizationProfile must be either TCP or TCP_LEGACY.

I'm going to reach out to the CloudControl team to see what we're missing (if anything) and get back to you as soon as I hear from them.

**Comment by adrianriobo** [comment]
Cool, 

Keep waiting here from you!

**Comment by tintoy** [comment]
Ok, I think I see the problem; the part of the provider that handles `ddcloud_virtual_listener` is calling an older version of the CloudControl API (which doesn't support SSL offload). I'm going to switch it over and see what happens.

**Comment by tintoy** [comment]
Yep, that fixed it. I'll put together a release shortly.

Note - due to a change in the CloudControl API, the `optimization_profiles` (list) property on `ddcloud_virtual_listener` is now `optimization_profile` (string).

**Comment by tintoy** [comment]
Ok - can you give [v1.3.3](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases/tag/v1.3.3) a try?

**Comment by adrianriobo** [comment]
Hi writing from my phone...it 8 P.M. here Spain...so tomorrow i Will give a try first thing in the morning ...and I will write you back

**Comment by tintoy** [comment]
No problem - take your time :)

**Comment by adrianRiobo** [comment]
Hi, I already installed version 

`terraform-provider-ddcloud v1.3.3 (62dda3f74a769a693a691ccd184e39fc1f6a68f1)`

But now I am getting this error during plan phase:

> Error: module.vip.ddcloud_virtual_listener.default: : invalid or unknown key: optimization_profiles

Previous version had this attribute, but now I deleted, so my virtual listener resource looks like:

`resource "null_resource" "virtuallistener_syncronizer" {
  triggers {
    dependency_id = "${var.sync_virtuallistener}"
  }
}

resource "ddcloud_virtual_listener" "default" {

    name                    = "virtuallistener_${var.name}"
    protocol                = "${var.protocol}"
    pool                    = "${ddcloud_vip_pool.default.id}"
    ssl_offload_profile     = "${var.ssl_offload_profile}"
    persistence_profile     = "${var.persistence_profile}"
    networkdomain           = "${var.networkdomain}"

    depends_on = ["null_resource.virtuallistener_syncronizer"]}

As you can see no optimization_profiles at all... I also added debug for logging.. and I am seeing this:

> 2018/03/15 08:24:01 [ERROR] root.vip: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [: invalid or unknown key: optimization_profiles]
2018/03/15 08:24:01 [ERROR] root.vip: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [: invalid or unknown key: optimization_profiles]
2018/03/15 08:24:01 [TRACE] [walkValidate] Exiting eval tree: modul- *terraform.NodeValidatableResourceInstance

If you need full stack or something just let me know.

**Comment by tintoy** [comment]
BTW if you have an existing .tfstate file you may need to edit it manually to rename the optimization_profiles property to optimization_profile and change its type from an array to a string (that's a one-off though).

**Comment by adrianriobo** [comment]
Yes, no problem I cleaned everything and now this problem does not exist anymore... but now I am getting...

> ddcloud_ssl_domain_certificate.default: Request to import SSL domain certificate 'sophie-certificate' failed with status code 400 (INVALID_INPUT_DATA): key must be provided.

But resources are exactly the same like previous executions where no problems with certificate...

**Comment by tintoy** [comment]
Hmm, can you run it with logging and attach the log?

**Comment by adrianriobo** [comment]
Yes just one sec

**Comment by adrianriobo** [comment]
Seems something with private_key in changelog of this version

[ssldomaincertificate.log](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/files/1814524/ssldomaincertificate.log)

Request body is not including key.. or at least not key value ..."key":""

**Comment by tintoy** [comment]
Only difference is that we never treat it as changed. If it's the first time a resource is being created that doesn't even get called.

I'll pick this up tomorrow :)

**Comment by tintoy** [comment]
(bedtime)

**Comment by adrianriobo** [comment]
yes no problem...we will talk tomorrow...have a good rest!

**Comment by tintoy** [comment]
In the meanwhile if you can attach the logs (or email to adam dot friedman at Dimension Data dot com) I'll have a look first thing tomorrow

**Comment by adrianriobo** [comment]
Yes you already have it in previous comment..here you have again:

[ssldomaincertificate.log](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/files/1814524/ssldomaincertificate.log)

As I see...in first creation ... of ssl domain certificate..now private key is ignored....so its value is not passed in the request body...

**Comment by tintoy** [comment]
Sorry, I thought I'd tested that before creating the release! I'll try it again in about an hour or so when I get into the office.

**Comment by tintoy** [comment]
Nope, looks like I must have made a mistake while testing it. Sorry for wasting your time :-(

I've fixed the issue (and tested it twice) so I'll put out a new release shortly.

**Comment by tintoy** [comment]
Ok @adrianRiobo, [v1.3.4-alpha1](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases/tag/v1.3.4-alpha1) is ready to go :)

If that works for you, let me know and I'll create the RTM release.

**Comment by tintoy** [comment]
PS. Sorry again for wasting your time, I'll try to be more thorough with my testing next time!

**Comment by adrianriobo** [comment]
Sorry I ve been offline..no apologies...the goal is improve...I will try
right now and I talk you back

**Comment by tintoy** [comment]
No worries, take your time :)

**Comment by adrianriobo** [comment]
Hi there, now everything looks right... everything was created and everything set correct.

Cheers I think you could create release... I close this issue as solved.. and keep waiting for release version.

Good weekend and thanks for everything!

**Comment by tintoy** [comment]
Thanks for testing it! Will create a new release first thing Monday.
