### ISSUE TITLE
Update virtual listener documentation

### ISSUE THREAD

**Issue by adrianriobo** [DimensionDataResearch/terraform-provider-ddcloud#111]
As it says in [virtual listener doc](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/development/v1.3/docs/resource_types/virtual_listener.md):

optimization_profile is required in convination: STANDARD + TCP 

but STANDARD + HTTP is also mandatory..checked from cloudcontrol api response:

`failed with status code 400 (CONFIGURATION_NOT_SUPPORTED): optimizationProfile is required for type STANDARD and protocol HTTP`

**Comment by tintoy** [comment]
Thanks! I'll get that updated.

**Comment by tintoy** [comment]
Done :)
