### ISSUE TITLE
Terraform fails when attempting to include a disk which is bigger than the standard OS images

### ISSUE THREAD

**Issue by adrianvolpe** [DimensionDataResearch/terraform-provider-ddcloud#114]
Prior to Cloud Control 2.7 (2.6) a `ddcloud_server` resource could be defined with the following attributes:
` disk {
        scsi_unit_id     = 0
        size_gb          = 100
        speed            = "HIGHSPEED"
    }`

Since the 2.7 upgrade terraform fails with the following message:
````
3 error(s) occurred:

* module.emr_environment.module.emr_eis_mongodb_server.ddcloud_server.emr_server: 1 error(s) occurred:

* ddcloud_server.emr_server: Request to add disk with SCSI Unit ID 1 to server '9e60e9e1-d644-4a69-a80b-c76baf5ab13d' failed with status code 400 (SERVER_STARTED): Server with id 9e60e9e1-d644-4a69-a80b-c76baf5ab13d is started but must be stopped to perform this operation. Please Power Off or Shutdown the Server (as appropriate) and try again.
````

The Cloud Control API release notes say that the server must be off to resize a disk.  So if the VM is shutdown terraform then thinks it needs to recreate the resource instead of extend it.  

Using:
Terraform v0.11.7
+ provider.ddcloud (unversioned)
+ provider.null v1.0.0

The ddcloud provider is version 1.34

**Comment by tintoy** [comment]
Yep, that sounds like a bug to me.

I'm a little flat-out at the moment (recent internal org changes mean this project is being transferred elsewhere within DD but none of that has been finalised), so it may be a week or so before I get to this; if that's too slow and you're up to it I'd be happy to accept a pull-request :)

**Comment by adrianvolpe** [comment]
Thanks @tintoy. Yeah I'm in the middle of a change so I am working around it for the moment.  I think it may be just the EU8 environment at the moment.  I'm not taking any chances but I will do some more investigating once the change is completed.

**Comment by adrianvolpe** [comment]
Hi @tintoy I've had a look at the code with Stuart Campbell and we think the way to fix this issue is to modify the `createDisks` function in `resource_server_disks.go`

So before `processModifyDisks()` or `processAdddisks()` we would need to ensure the server was in a state of `"started == false"` then do the disk changes and if it server was configured with auto started restart the server after the disk changes.

If you are happy for us to try this I can do a pull request to attempt this.

**Comment by tintoy** [comment]
That sounds correct to me - by all means, please go ahead and create a PR! I'm happy to review and offer advice if required :)

PS. Thanks for having a go!

**Comment by tintoy** [comment]
From memory there's already a function you can use to stop / start the VM

**Comment by adrianvolpe** [comment]
@tintoy I did a build of my modified terraform provider for ddcloud (which was a little bit of a challenge)!  Now I'm trying to test it against my terraform configuration but am getting this error:
````
* module.emr_environment.module.emr_trap_collector_edc_server.ddcloud_server.emr_server: 2 error(s) occurred:

* module.emr_environment.module.emr_trap_collector_edc_server.ddcloud_server.emr_server[0]: ddcloud_server.emr_server.0: failed to retrieve backup details of server '536faf4a-485a-41de-b058-f38592b341e6' (HTTP 403 / REASON_140): User Adrian_Volpe_EMR does not have authority to perform 'Get Backup Details' operation
````

Is there a way I can turn off the get backup details?  I don't think it is in the current driver version.

**Comment by tintoy** [comment]
Not easily, unfortunately - if we simply ignore the error then the providers behaviour is not consistent. We could add a provider property to turn it off but that needs a bit of thought. For now you could comment it out to work around if you can't get backup permissions. I'll see what we can do about the provider-level switch.

**Comment by adrianvolpe** [comment]
Ok I've made progress but am seeing the following:

````
Error: Error applying plan:

3 error(s) occurred:

* module.emr_environment.module.emr_firewall_rules.ddcloud_firewall_rule.permit_all_snmptraps_to_tcp_trap_vip: 1 error(s) occurred:

* ddcloud_firewall_rule.permit_all_snmptraps_to_tcp_trap_vip: Request to create firewall rule in network domain '959e4102-5d6c-406d-b4fd-6c2418d0c51e' failed with unexpected status code 400 (NAME_NOT_UNIQUE): Name 'PERMIT_ALL_SNMPTRAPS_TCP_TO_TRAP_VIP' is not unique for Network Domain 959e4102-5d6c-406d-b4fd-6c2418d0c51e.
* module.emr_environment.module.emr_gen_mongodb_server.ddcloud_server.emr_server: 1 error(s) occurred:

* ddcloud_server.emr_server: Request to delete server failed with unexpected status code 400 (SERVER_STARTED): Server with id 14e43485-b828-4583-bfbb-570abdbd6604 is started.
* module.emr_environment.module.emr_eis_mongodb_server.ddcloud_server.emr_server: 1 error(s) occurred:

* ddcloud_server.emr_server: Request to delete server failed with unexpected status code 400 (SERVER_STARTED): Server with id 3f2016e2-c19c-4ae3-a5e9-e3eb0ad34843 is started.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
````

I'm not sure why terraform thinks it needs to destroy the server when I am just modifying the disk size.  The shutdown and start seem to be working.  The issue about firewall rules has always been there so ignore that.  Where can I see the debug log?

**Comment by tintoy** [comment]
To log pretty much everything:

```bash
export TF_LOG_DEBUG
export MCP_EXTENDED_LOGGING=1
```

I can't remember if the provider is supposed to shut down the server before destroying it, but I would have thought so...

From memory, when you run `terraform plan` it should tell you which changed property requires the server to be destroyed and recreated.

**Comment by adrianvolpe** [comment]
I should have included this in the above:

````
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  ~ module.emr_environment.module.emr_eis_mongodb_server.ddcloud_server.emr_server
      auto_start:            "" => "false"
      disk.0.size_gb:        "10" => "100"

  + module.emr_environment.module.emr_firewall_rules.ddcloud_firewall_rule.permit_all_snmptraps_to_tcp_edc_trap_vip
      id:                    <computed>
      action:                "ACCEPT_DECISIVELY"
      destination_address:   "168.128.108.233"
      destination_port_list: "568b0ac9-4b29-45ae-9b1e-2a3fc051b60a"
      enabled:               "true"
      ip_version:            "ipv4"
      name:                  "PERMIT_ALL_SNMPTRAPS_TCP_TO_EDC_TRAP_VIP"
      networkdomain:         "959e4102-5d6c-406d-b4fd-6c2418d0c51e"
      placement:             "after"
      placement_relative_to: "PERMIT_ALL_SNMPTRAPS_UDP_TO_TRAP_VIP"
      protocol:              "tcp"

  + module.emr_environment.module.emr_firewall_rules.ddcloud_firewall_rule.permit_all_snmptraps_to_tcp_trap_vip
      id:                    <computed>
      action:                "ACCEPT_DECISIVELY"
      destination_address:   "168.128.108.232"
      destination_port_list: "568b0ac9-4b29-45ae-9b1e-2a3fc051b60a"
      enabled:               "true"
      ip_version:            "ipv4"
      name:                  "PERMIT_ALL_SNMPTRAPS_TCP_TO_TRAP_VIP"
      networkdomain:         "959e4102-5d6c-406d-b4fd-6c2418d0c51e"
      placement:             "after"
      placement_relative_to: "PERMIT_ALL_AMQP_TO_VIP"
      protocol:              "tcp"

  + module.emr_environment.module.emr_firewall_rules.ddcloud_firewall_rule.permit_all_snmptraps_to_udp_edc_trap_vip
      id:                    <computed>
      action:                "ACCEPT_DECISIVELY"
      destination_address:   "168.128.108.233"
      destination_port_list: "568b0ac9-4b29-45ae-9b1e-2a3fc051b60a"
      enabled:               "true"
      ip_version:            "ipv4"
      name:                  "PERMIT_ALL_SNMPTRAPS_UDP_TO_EDC_TRAP_VIP"
      networkdomain:         "959e4102-5d6c-406d-b4fd-6c2418d0c51e"
      placement:             "after"
      placement_relative_to: "PERMIT_ALL_SNMPTRAPS_TCP_TO_EDC_TRAP_VIP"
      protocol:              "udp"

  + module.emr_environment.module.emr_firewall_rules.ddcloud_firewall_rule.permit_all_snmptraps_to_udp_trap_vip
      id:                    <computed>
      action:                "ACCEPT_DECISIVELY"
      destination_address:   "168.128.108.232"
      destination_port_list: "568b0ac9-4b29-45ae-9b1e-2a3fc051b60a"
      enabled:               "true"
      ip_version:            "ipv4"
      name:                  "PERMIT_ALL_SNMPTRAPS_UDP_TO_TRAP_VIP"
      networkdomain:         "959e4102-5d6c-406d-b4fd-6c2418d0c51e"
      placement:             "after"
      placement_relative_to: "PERMIT_ALL_SNMPTRAPS_TCP_TO_TRAP_VIP"
      protocol:              "udp"

  ~ module.emr_environment.module.emr_gen_mongodb_server.ddcloud_server.emr_server
      auto_start:            "" => "false"
      disk.0.size_gb:        "10" => "100"

Plan: 4 to add, 2 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: prod_foxtrot.plan

To perform exactly these actions, run the following command to apply:
    terraform apply "prod_foxtrot.plan"
````

So no destroy was planned yet that was an error I got.  With those logging options I should get a better idea as to what the system is doing.  Given I had never touched the go lang before today I'm pretty happy with this progress.

**Comment by tintoy** [comment]
Ok, that's pretty odd. As far as I know, if no destroy is shown in the `plan` stage, it should be impossible for Terraform to then decide to destroy that resource during the `apply` stage (that'd make a mockery of the concept of `terraform plan`). Perhaps it's a Terraform bug?

Glad to hear you're coming to grips with it all; I'll try to pitch in as soon as I can, but it's looking like I still have a couple of days before I can dig into the code :-/

**Comment by tintoy** [comment]
If you can capture the full debug log and email it to me I'll have a look and see if anything stands out.

**Comment by tintoy** [comment]
One thing you can try is running `terraform plan -out=my.plan` then `terraform apply my.plan` to see if the same behaviour occurs.

**Comment by tintoy** [comment]
As for the firewall thing, manually deleting the rule and then running `terraform apply` should do the trick.

**Comment by tintoy** [comment]
Finally got a chance to look at the restart thing; I pushed (https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/commit/a204a27bd634124898298a51041c8af397db7d04) a possible solution to the `feature/server-disk-restart` branch. How close is it to your solution?

**Comment by adrianvolpe** [comment]
Hi @tintoy! The same idea but I was shooting in the dark.  I didn't realise that when you do a 
````
apiClient.GetServer(serverID)
````
The result is an instance of the resource_server.go object and so you can then just call `server.serverShutdown()` and `serverStart()`

I also had to make a few tweaks to the Vagrant file:
 - Changed `GOVERSION="1.10.1"`
- Added the following lines after `go get -u github.com/hashicorp/terraform`:
`````
go get -u golang.org/x/crypto/pkcs12
go get -u github.com/pkg/errors
`````

I couldn't check my code in not sure if that's an issue on the project or just my account on github.

**Comment by tintoy** [comment]
Sorry for the delay on this, I've been tied up with a bunch of other work. I'll try to get a release out sometime today.

**Comment by tintoy** [comment]
Ok @adrianvolpe - could you give [v1.3.7](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases/tag/v1.3.7) a try when you get a chance? The provider should now stop / start the server (when required), before / after modifying its disk configuration.

Thanks!

**Comment by adrianvolpe** [comment]
Hi Adam,

Not sure if its working for me or not as I keep getting a Terraform crash.  I’ve attached a zip of the crash log.  Seems to be after it can’t find a resource.

Cheers,

Adrian

**Comment by tintoy** [comment]
Sorry it looks like the attachment didn't come through via email - would you be able to attach it via the web UI?

**Comment by adrianvolpe** [comment]
[crash.log.zip](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/files/1978270/crash.log.zip)

I thought I may have commented out a line that was required but its still failing.  I wonder if the MCP API is playing up

**Comment by tintoy** [comment]
Ugh. DNS filtering in the office means I can't download it >:-(

Would you mind emailing it to me directly? Sorry!

**Comment by tintoy** [comment]
Ok, looks like there was a bug in the code that handles server network adapters (should have bailed out if the server does not exist, but it simply logged a message and continued on to the location where the crash occurred). [v1.3.8](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases/tag/v1.3.8) is [building now](https://travis-ci.org/DimensionDataResearch/dd-cloud-compute-terraform/builds/375721475) and the CI build process will publish the binaries into that release when it's done :)

**Comment by tintoy** [comment]
Ok it's ready to go.

**Comment by samuelchong** [comment]
Closing issue.  Looks like @tintoy has provided a fix from the comment above. @adrianvolpe pls reopen if you are still experiencing issue.
