### ISSUE TITLE
No binaries for 1.3.5

### ISSUE THREAD

**Issue by liger1978** [DimensionDataResearch/terraform-provider-ddcloud#115]
Hi, can you add the binaries to the 1.3.5 release please?

**Comment by tintoy** [comment]
Sure - sorry I can't do it until I get into the office tomorrow (it's 10pm here in AU) but I'll publish them then.

**Comment by tintoy** [comment]
On my way into the office now. I keep meaning to alter the CI build to publish its binaries, will have a go at doing so sometime today.

**Comment by tintoy** [comment]
Hi - sorry for the delay, binaries are published now.

I've also fixed the CI build so it will automatically publish binaries when a new release tag is created.

**Comment by liger1978** [comment]
Thanks. Those binaries seem to be labelled as 1.3.6 but the release is 1.3.5?

**Comment by tintoy** [comment]
Yeah, looks like the version info is slightly off; it's 1.3.6

**Comment by tintoy** [comment]
Ok, I've just published v1.3.7 where the version info is back in sync; feel free to reopen this issue if you need to :)
