### ISSUE TITLE
Canada API url is incorrect!?

### ISSUE THREAD

**Issue by phillogic** [DimensionDataResearch/terraform-provider-ddcloud#117]
Hello
 When using the terraform provider for creating a network domain in Canada we get an error saying api url cannot be reached. On further research it would seem that the the provider needs to be updated to use the correct url for canada as per image below

`Error: Error applying plan:

1 error(s) occurred:

* ddcloud_networkdomain.my-domain: 1 error(s) occurred:

* ddcloud_networkdomain.my-domain: Unexpected error while performingst to '**https://api-ca.dimensiondata.com/oec/0.9/myaccount**': Get httpimensiondata.com/oec/0.9/myaccount: dial tcp: lookup api-ca.dimensio 10.65.64.11:53: no such host: Get https://api-ca.dimensiondata.com/count: dial tcp: lookup api-ca.dimensiondata.com on 10.65.64.11:53:

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
`
The actual url should be L Canada - https://api-canada.dimensiondata.com

**Comment by samuelchong** [comment]
* `region` - (Optional) The Managed Cloud Platform region code (e.g. 'AU' - Australia, 'EU' - Europe, 'NA' - North America) that identifies the CloudControl end-point to connect to.  
Must specify exactly one of either `region` or `cloudcontrol_endpoint`.
* `cloudcontrol_endpoint` - (Optional) The base URL of the CloudControl end-point to connect to.  
Use this property if you are using PCEE or some other custom end-point that does not follow the standard pattern (`https://api-<region>.dimensiondata.com/`).  
Must specify exactly one of either `cloudcontrol_endpoint` or `region`.

**Comment by samuelchong** [comment]
Use 'canada' as the region code.
