### ISSUE TITLE
Doesn't work with terraform v1.12

### ISSUE THREAD

**Issue by muyiscoi** [DimensionDataResearch/terraform-provider-ddcloud#132]
Using the latest version of both terraform (1.12.4) and the dd-cloud provider (2.2.2).
After performing a `terraform init`, a `terraform plan` displays the following error

```
$ ./terraform plan -out tf.plan

Error: Failed to instantiate provider "ddcloud" to obtain schema: Incompatible API version with plugin. Plugin version: 4, Client versions: [5]``` 

Worked successfully with older version of terraform (1.11.14)

**Comment by samuelchong** [comment]
terraform v1.12 not supported at this stage. works required.

**Comment by adrianvolpe** [comment]
Hi. @samuelchong  Can you please give an update. It's November and Terraform is now up to v1.12.16.     I'd prefer to be using a version of 1.12.x instead of 1.11.x

**Comment by samuelchong** [comment]
I will get to that when I have bandwidth.

**Comment by nwright-nz** [comment]
@adrianvolpe - Theres an open PR for this now - but if you want to test it right now, feel free to build the provider yourself. I've run it through acceptance tests with no major issues.

**Comment by samuelchong** [comment]
Thx @nwright-nz. I've released a beta build. v3.0.1.
