### ISSUE TITLE
PROVISIONEDIOPS disks not supported

### ISSUE THREAD

**Issue by stroebs** [DimensionDataResearch/terraform-provider-ddcloud#137]
STANDARD, ECONOMY and HIGHPERFORMANCE are all supported but not PROVISIONEDIOPS. With the latest changes made by MCP that throttled disks to a slow crawl, we require the use of PROVISIONEDIOPS disks.

**Comment by samuelchong** [comment]
Implementing this feature now. You will have it soon.

**Comment by stroebs** [comment]
Thanks @samuelchong - I worked around it by building the module locally and modifying the classes to accept PROVISIONEDIOPS.

**Comment by samuelchong** [comment]
IOPS implemented. Available in release terraform-provider-ddcloud v2.3.2
