### ISSUE TITLE
Version number missing from latest GitHub release tag

### ISSUE THREAD

**Issue by liger1978** [DimensionDataResearch/terraform-provider-ddcloud#143]
For latest release v2.3.3, the version number is missing from the GitHub release tag

**Comment by samuelchong** [comment]
it's there.

**Comment by liger1978** [comment]
v2.3.3 is marked as pre-release. Is this correct?

**Comment by samuelchong** [comment]
Yes, I'm doing some testing and also waiting for feedback from other before making it official. So far, no issue has been reported. Feel free to use it and provide feedback. Thx.
