### ISSUE TITLE
dd_cloud_vip_pool - How do you assign nodes to the pool?

### ISSUE THREAD

**Issue by wninobla** [DimensionDataResearch/terraform-provider-ddcloud#18]
I was reading the documentation so unless its not documented I have no way to add nodes that are defined with ddcloud_vip_node to the ddcloud_vip_pool resource command.  Is this missing or just not documented?

**Comment by tintoy** [comment]
Sorry, my bad - it _is_ documented but the [page](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/development/v1.0/docs/resource_types/vip_pool_member.md) is not linked from the [main documentation page](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/tree/development/v1.0/docs).

I'll get that sorted out.

**Comment by tintoy** [comment]
Thanks for reporting that - I've added the missing link to the documentation index.

**Comment by wninobla** [comment]
Great - thanks!  Now I can test that part of my integration.  All the other stuff I got working.  I didn't write it out to a plan first so after I did errors magically went away...

Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data
