### ISSUE TITLE
Request for Enhancement - Reference to add firewall acl's via ip and port lists

### ISSUE THREAD

**Issue by wninobla** [DimensionDataResearch/terraform-provider-ddcloud#22]
Hi,

I was looking to consume more granular firewall rules so I can insert servers into port group lists and ip lists.  Is that already a feature or something that needs developing?

**Comment by tintoy** [comment]
The underlying support is there (in the CloudControl client for Go), but our Terraform provider doesn't expose it yet.

Should be fairly simple to implement, just didn't have time to do it for v1.0.

I'll create some backlog items for this on Wednesday (probably a v1.1 timeframe, so at least a couple of weeks out depending on scheduling).

**Comment by wninobla** [comment]
OK cool.  I see this being a problem for really big environments where it'll be easier to reference a list vs. writing individual rules.  I will close this oen for now since you're tracking it in a different ticket.  Thanks!

**Comment by tintoy** [comment]
Tracked via #30 and #31.
