### ISSUE TITLE
Request for Enhancement - Access to enable services including BaaS and MaaS

### ISSUE THREAD

**Issue by wninobla** [DimensionDataResearch/terraform-provider-ddcloud#23]
Hi,

Looking to see if we can enable these services or not.  The resources aren't defined in the docs so I am guessing this is a net new ask?  Do let me know where this one sits in development.  Thanks.

**Comment by tintoy** [comment]
Hi - originally, I considered these to be out of scope for being managed by Terraform; I've tried to be mindful of not putting stuff into Terraform that doesn't belong there (i.e. configuration that's likely to be changed by other non-Terraform methods after deployment).

Having said that, several people have asked for this now, so I'll have a chat to @BenObermayer later this week and see what we can do :)

Could you list out what you consider the order of priority for these features? It'll give me a starting point for what gets looked at when.

**Comment by wninobla** [comment]
Priority wise, I'd say MaaS is more of an issue since the auto scaling is tied to that.  Then BaaS afterwards since I agree with you in that its more of a manual configuration item.

**Comment by BenObermayer** [comment]
Monitoring is an on / off flag so it should be pretty easy to be part of the deployment even though it needs to happen after the server has been deployed.

Backup is a little more complicated as it has an on / off flag, but you then also need to download and install the backup client on the server.  I don't think this later portion can be done by Terraform.  You would need to use a tool like ansible to install it.  

I think it would be good if Terraform can do all the pre-setup for backup, ie. Enable it and Enable backup clients.  It's then ready for the agent to be installed.  There could be a Agent download URL property a configuration tool could use to do the rest.  How does that sound?

**Comment by tintoy** [comment]
Ok that sounds pretty doable. I'll split this out into 2 separate issues (one for MaaS, and one for BaaS).

**Comment by tintoy** [comment]
Moved to #26 and #27.

**Comment by wninobla** [comment]
For MaaS would you then create the auto scale features there or attach it to a separate resource call?

**Comment by tintoy** [comment]
Don't know anything about the auto-scaling stuff at this stage, I'll have to do some research and get back to you...

**Comment by wninobla** [comment]
Yeah they are values on another tab in the MaaS stuff that the VM team wrote.  Hopefully its an easy conversion?

**Comment by tintoy** [comment]
I'll have a look and let you know :)

**Comment by tintoy** [comment]
Will track this in #28.
