### ISSUE TITLE
Server anti-affinity support

### ISSUE THREAD

**Issue by wninobla** [DimensionDataResearch/terraform-provider-ddcloud#24]
Hi,

Looking to consume the server anti-affinity rules here.  Let me know if this is in development or not.  Thanks!

**Comment by tintoy** [comment]
Currently this wasn't even on the roadmap (i.e. I don't even know what's involved in implementing it), but I'll add an item to our backlog to investigate it.

Level of priority?

**Comment by wninobla** [comment]
I would say since we tie SLA's to it we'll want to mark this at least as a minimum if not a high only because we don't necessarily do containers fully just yet.  nothing is considered a throw away yet so we need to provide some fault tolerance here at the VM level.

**Comment by tintoy** [comment]
Ok - duly noted, will put this near the top of the pile :)

**Comment by BenObermayer** [comment]
It's one API to enable with the 2 server IDs, so should be pretty simple to add.

**Comment by tintoy** [comment]
Work remaining:
- [x] CloudControl API client
  - [x] Unit tests
- [ ] ddcloud_anti_affinity_group resource type
  - [ ] Acceptance tests
  - [ ] Documentation

**Comment by tintoy** [comment]
Looks to be pretty simple, so hopefully I can knock this one off today.

**Comment by tintoy** [comment]
Just waiting for last run of automated acceptance tests...
