### ISSUE TITLE
Additional NIC support for servers

### ISSUE THREAD

**Issue by tintoy** [DimensionDataResearch/terraform-provider-ddcloud#33]
Because all properties of CloudControl's representation of a NIC can be changed after deployment they cannot (unlike, say, server disks) be declared as items on a server. Instead, they need to be a separate resource type so their life-cycle can be separately tracked.

Implement a `ddcloud_server_nic` resource type that adds a NIC to a `ddcloud_server`.
In much the same way as we currently have a [lock per network domain](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/development/v1.0/vendor/ddcloud/provider.go#L160), we may need to also implement a lock per server.
- [x] Per-server lock
- [x] `ddcloud_server_nic` resource type
  - [x] Implementation
  - [x] Unit tests
  - [x] Integration tests

**Comment by wninobla** [comment]
For this one I'm sure you already know but the initial NIC is defined as the primary NIC and may not be deleted once the box is instantiated for its lifetime.  All other NICs are subject to any and all changes.  Just my two cents worth whether you needed it or not... =)

**Comment by tintoy** [comment]
@wninobla thanks! Always good to get real-world feedback 👍

This is definitely only for additional NICs, the primary one will continue to be declared directly on the `ddcloud_server` resource.

**Comment by wninobla** [comment]
Great!  I look forward to all the innovation I'm stirrng up.  =)  Now if I can start to level up my ansible and get the CI stuff up and running thereafter I'll feel like a IT devops dude...

**Comment by tintoy** [comment]
Implemented as `ddcloud_server_nic` resource type.
