### ISSUE TITLE
Question - Easy way to pull master list of attributes for Terraform objects?

### ISSUE THREAD

**Issue by wninobla** [DimensionDataResearch/terraform-provider-ddcloud#36]
Hi,

Is there an easy way to pull all of the live attributes that are associated with a resource so that I can get more granular in what I choose as a variable or the like?  Is it in the API guide or is this a subset of items that are unique to Terraform and the DD plugin?  Please advise as I'd rather be able to iterate a list out for testing or have a document on the same vs. guessing.  That is to say assuming this doesn't already exist in some capacity.  Thanks in advance!

**Comment by tintoy** [comment]
Do you mean what attributes are available to set for each resource `ddcloud` resource type?

**Comment by tintoy** [comment]
If so, [the documentation](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/tree/development/v1.0/docs) for a specific resource type should be your first port-of-call (but [let us know](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/issues/new) if you find something missing).

**Comment by wninobla** [comment]
Well yes and no.  You have the documents do I can read that.  I was thinking of objects I can use to use variables on.  I can call I think terraform show as that'll dump what it sees on an object.  That'll do for now...  

Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data

**Comment by tintoy** [comment]
Sorry, I’m not sure I understand what you’re asking - when you say objects you can use variables on, do you mean what sort of expressions are valid as values for attributes of resources?

**Comment by wninobla** [comment]
Its the latter...  I think I got it figured out though.  I should have said attributes for the resulting objects Terraform creates (i.e. the underlying cloud control VM's, networks, VIP's etc.)  Sorry, my brain isn't working too well... =)  Anyhow, I think I have a handle on it for now as I figured out that when you use counts the name of the object gets appended with the variable key.  I was finding a way to assign the firewall rules for instance after the fact but as I said I think I'm good.  Again, its the follies of not being a devops dude 24x7.

Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data

**Comment by tintoy** [comment]
Sorry I get it now :)

Later, I'll post a link to our Terraform configuration for Mantl - it has examples of stuff like that.

**Comment by tintoy** [comment]
Also, see the section in Terraform docs on interpolation syntax in config. Element function may do what you want.

**Comment by wninobla** [comment]
OK cool.  In the meantime once I get the other content updated (along with the naming) I'll post the simple examples on the counts I did.  Not terribly complicated but it was a pain to figure out.  Only took a few hours though...

Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data

**Comment by wninobla** [comment]
Yeah I saw that but that didn't work as I expected since in some cases I needed a string vs. dynamically forming a variable.  What I need to do is to write a template and then output the new variable for stuff like depends_on for instance.  But, as I get better at that all I'll get more snazzy.

Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data

**Comment by tintoy** [comment]
Ok, @wninobla - is this issue resolved, now that we've merged the samples link?

**Comment by tintoy** [comment]
Closing for now - ping me if you want to reopen :)
