### ISSUE TITLE
Add "cores per socket" and "cpu speed" features to ddcloud_server resource

### ISSUE THREAD

**Issue by wninobla** [DimensionDataResearch/terraform-provider-ddcloud#37]
Hi,

I was looking at the attributes in building my Terraform script and noted that the resource ddcloud_server has no reference to manipulate CPU cores - only cpuCount.  I see the following in the XML example on page 268 in v2.3 of the API documentation:

```
<reconfigureServer id="7389da66-7685-400a-81ca-665781076bb1" xmlns="urn:didata.com:api:cloud:types">
   <memoryGb>8</memoryGb>
   <cpuCount>5</cpuCount>
   <cpuSpeed>HIGHPERFORMANCE</cpuSpeed>
   <coresPerSocket>1</coresPerSocket>
</reconfigureServer>
```

I would propose we add both coresPerSocket and cpuSpeed to get this in more of an automated deployment.  We can alternatively set it on the template level but it would take away from having one global set of templates and then spawning different resource configurations off of the same.

Please advise or let me know if its elsewhere where I'm not looking... =)  Thanks!

**Comment by tintoy** [comment]
Hi.

Yep, this is an easy one to implement (just didn't have time to put it into the initial release).
- [x] Implementation
  - [x] `cores_per_cpu`
  - [x] `cpu_speed`
- [x] Documentation for additional attributes
