### ISSUE TITLE
Question - ddcloud_address_list instructions for child_lists option not defined

### ISSUE THREAD

**Issue by wninobla** [DimensionDataResearch/terraform-provider-ddcloud#40]
Hi,

I have the other options working but was trying to use the optional child_lists feature.  I get the error:
- ddcloud_address_list.production-list: child_lists: should be a list

So, I am unsure on the syntax in how to represent this option.  So, if you can update the documentation on the same that would be great.  BTW, the documentation refers to port_lists in the address_list readme file so you will want to update that also.  Thanks.

**Comment by wninobla** [comment]
This is the same issue for the resource ddcloud_port_list.

**Comment by wninobla** [comment]
The final note here is whether or not the ddcloud_firewall_list has updates to utilize the new resources ddcloud_address_list and ddcloud_port_list respectively.  Is this code written but not released or in flight?

**Comment by tintoy** [comment]
No it should definitely work - I updated the docs before I went on leave. I'll have a look at this tomorrow.

**Comment by tintoy** [comment]
Should be enough to just put a list of comma-separated entries in square brackets.

Same syntax as depends_on.

**Comment by tintoy** [comment]
I see - yes address lists are supported for `ddcloud_firewall_rule`, but I didn't specify the property names for address lists in the documentation. I'll update the docs, but for reference here are the 4 properties relating to address / port lists (source / destination) on a firewall rule:
- `source_address_list`
- `source_port_list`
- `destination_address_list`
- `destination_port_list`

**Comment by tintoy** [comment]
This should be fixed now, @wninobla. Can you take a look at let me know?

**Comment by wninobla** [comment]
OK, this looks good now.  I will test the ID and see if the ddcloud_firewall_acl gets updated now.  What I didn't see or rather would like an example of is the list that you were talking about if I specify multiples for the ddcloud_address/port_list.  I can play around with it but if you can update the docs that specify that example or just send me one I can update my project to reflect the same.  Thanks in advance!

BTW, I talked with Hashicorp just now and looking to play with their Atlas/Terraform Enterprise shim.  Should be interesting to say the least. =)

**Comment by tintoy** [comment]
@wninobla does that suit?

**Comment by wninobla** [comment]
Well yeah and no.  I was looking for a child_list example.  For instance:

1)  I have (2) resources defined as ADDRLIST_01 and ADDRLIST_02 that I want to combine

2)  I define a new resource as GROUP_01 to hold the items above as a single list

**Comment by tintoy** [comment]
Oh, sorry I thought that was obvious. Obviously not now that I think about it. Sorry, my bad 😊

I'll add one.

**Comment by wninobla** [comment]
BTW, it fails also because it has as a required component the name and address fields...  So I can fill the name one but the address field doesn't necessarily make sense.  The IP_version I think got truncated in the doc so you'll want to readd that in there also.

**Comment by wninobla** [comment]
No worries.  We often make the assumption including myself on what's intended.  That's why I am working through the instructions as it gives a fresh view on it all.

**Comment by tintoy** [comment]
Sorry when you say address is required, where do you mean? Can you provide an example? Looking in the code, address is [marked as optional](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/development/v1.0/vendor/ddcloud/resource_address_list.go#L56).

**Comment by tintoy** [comment]
Oh, in the documentation. Sorry, yes, I'm stupid.

**Comment by tintoy** [comment]
@wninobla ok - how about now? 🌵

**Comment by wninobla** [comment]
It's OK.  I retried the syntax I used on Friday but for some reason it looks like its reading it now although when I run it I get this:

[root@192-168-104-251 test]# terraform apply
ddcloud_networkdomain.networkdomain: Refreshing state... (ID: 9c4033c9-3c2c-4ea0-bf20-52929c74140c)
ddcloud_address_list.utility-list: Refreshing state... (ID: 1c061f76-658a-4322-b606-dd6fa0a46104)
ddcloud_vlan.trust-vlan: Refreshing state... (ID: b2cfad36-061b-46dc-996b-0e490b05793e)
ddcloud_vlan.dmz-vlan: Refreshing state... (ID: d2473a60-75df-4b86-9d6f-cbd14783ea84)
ddcloud_address_list.trust-list: Refreshing state... (ID: d3a73729-d87f-4f6d-bf67-3d7b0c0bb52c)
ddcloud_address_list.dmz-list: Refreshing state... (ID: 01ec9196-7c1d-44f5-bc66-b80bb97f7190)
ddcloud_vlan.utility-vlan: Refreshing state... (ID: cd1e9af8-7062-466b-992e-e40a681f22c3)
ddcloud_port_list.http-alt-list: Refreshing state... (ID: d7de85ac-3f6a-4633-8198-e24fd67a9293)
ddcloud_port_list.http-list: Refreshing state... (ID: 274bad7f-9031-42c8-b349-2982a7b56182)
ddcloud_port_list.https-list: Refreshing state... (ID: e395809e-0232-406b-9a95-e3b8459559db)
ddcloud_server.webapp-server: Refreshing state... (ID: 6e1f29cf-08ad-4b62-b2b6-77b4802bf33a)
ddcloud_server.db-server: Refreshing state... (ID: b5f99711-8f46-4cec-b2c0-5361075f5f2b)
ddcloud_server_nic.webapp-server: Refreshing state... (ID: cfe129d0-6986-4e36-8723-16402925d322)
ddcloud_nat.nat: Refreshing state... (ID: 1bc62bd8-b06d-480e-b44f-c3196ff176a4)
ddcloud_server_anti_affinity.server_anti_affinity: Refreshing state... (ID: ae573a1d-1342-4946-9884-b31b6878596f)
ddcloud_vip_node.vip-node: Refreshing state... (ID: b27ebac9-8729-4c6a-a743-4f1ea8f2bdf5)
ddcloud_server_nic.db-server: Refreshing state... (ID: 3ceeed53-70b4-469b-9164-372ebaa7e06b)
ddcloud_firewall_rule.firewall-rule-001: Refreshing state... (ID: 5a8e6032-0e5b-4d1a-9608-9bc9a6c0dc6b)
ddcloud_vip_pool.vip-pool: Refreshing state... (ID: 78703344-ca07-4ba0-9c19-a2ba552163f6)
ddcloud_virtual_listener.virtual-listener: Refreshing state... (ID: 7a63c5f0-675f-4c89-bff6-d11c0d21f5ea)
ddcloud_vip_pool_member.pool_member: Refreshing state... (ID: 320e2f9f-e0e8-468f-855a-a40716d4d1c3)
ddcloud_firewall_rule.firewall-rule-002: Refreshing state... (ID: d84a355e-f73f-4593-a69d-0ece4a66072f)
ddcloud_address_list.prod-list: Creating...
  child_lists.#: "" => "2"
  child_lists.0: "" => "ddcloud_address_list.dmz-list"
  child_lists.1: "" => "ddcloud_address_list.trust-list"
  ip_version:    "" => "IPv4"
  name:          "" => "PROD_Address_List"
  networkdomain: "" => "9c4033c9-3c2c-4ea0-bf20-52929c74140c"
Error applying plan:

1 error(s) occurred:
- ddcloud_address_list.prod-list: Request to create IP address list 'PROD_Address_List' failed with status code 400 (RESOURCE_NOT_FOUND): IP Address List ddcloud_address_list.dmz-list not found.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

I'll now read ur docs and see what I'm doing wrong... =)

**Comment by wninobla** [comment]
OK I updated my .tf file and it won't take as its expecting a comma or something:

resource "ddcloud_address_list" "prod-list" {
  name                 = "PROD_Address_List"
  ip_version           = "IPv4"

  child_lists = [
    "${ddcloud_address_list.dmz-list.id}"
    "${ddcloud_address_list.trust-list.id}"
  ]

  networkdomain        = "${ddcloud_networkdomain.networkdomain.id}"
  depends_on           = ["ddcloud_networkdomain.networkdomain"]
}

Error is:

[root@192-168-104-251 test]# terraform plan
Error loading config: Error parsing /root/terraform/test/address_list.tf: At 58:2: error parsing list, expected comma or list end, got: STRING
[root@192-168-104-251 test]#

I'm not seeing the problem...  I know its simple but its not happy. =)

**Comment by wninobla** [comment]
OK it was missing the ending commas:

resource "ddcloud_address_list" "prod-list" {
  name                 = "PROD_Address_List"
  ip_version           = "IPv4"

  child_lists          = [
    "${ddcloud_address_list.dmz-list.id}",
    "${ddcloud_address_list.trust-list.id}",
  ]

  networkdomain        = "${ddcloud_networkdomain.networkdomain.id}"
  depends_on           = ["ddcloud_networkdomain.networkdomain"]
}

You will want to update the documentation in the child_lists section in your example to add commas...

**Comment by tintoy** [comment]
Ah, sorry - was typing that in a browser! Will fix :)

**Comment by tintoy** [comment]
Ok, so it works for you now?

**Comment by wninobla** [comment]
Address and port lists are working.  I an writing a firewall rule not and got the port list to work but its erroring on the address list specifically on the source.  The plan works but the apply doesn't.  I change it to both a nested and non nested address list with the same error.  Here's what I got:

resource "ddcloud_firewall_rule" "firewall-rule-004" {
  name                     = "mgmt.inbound"
  placement                = "last"
  action                   = "accept"
  enabled                  = true
  ip_version               = "ipv4"
  protocol                 = "tcp"
  source_address_list      = "${ddcloud_address_list.utility-list.id}"
  destination_address_list = "${ddcloud_address_list.prod-list.id}"
  destination_port         = "3389"
  networkdomain            = "${ddcloud_networkdomain.networkdomain.id}"
  depends_on               = ["ddcloud_virtual_listener.virtual-listener"]
}

Error applying plan:

1 error(s) occurred:
- ddcloud_firewall_rule.firewall-rule-004: Request to create firewall rule in network domain '9c4033c9-3c2c-4ea0-bf20-52929c74140c' failed with unexpected status code 400 (INVALID_INPUT_DATA): At least source ip or ipAddressListId must be provided.

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

Can you check to see if its a bug?

**Comment by tintoy** [comment]
Ok, I’ll have a look this afternoon (meetings until then). Sorry about that.

**Comment by wninobla** [comment]
No problem.  The regular rule works but when I specify any nested list it complains.  Just let me know what you find.

Also, on the child_lists portion, slight bug in that it keeps switching the list members and as a result it wants to modify the child lists back and forth every time I run a "terraform apply".  If you want me to I can file that under a separate case.

**Comment by tintoy** [comment]
@wninobla can you try running `terraform apply` again with the following environment variables set: 

`TF_LOG=DEBUG`
`TF_LOG_PATH=Apply.log`
`DD_COMPUTE_EXTENDED_LOGGING=1`

Then attach the generated log file?

**Comment by wninobla** [comment]
OK let me create a variable file and do that.  Just in time too as I just shut my session down... LOL

**Comment by tintoy** [comment]
Yeah please create a separate issue for that; it’s a bug (well, sort of) - CloudControl is not preserving the List order, so it should be changed to a Set instead.

**Comment by tintoy** [comment]
That should do it. Turns out CloudControl calls it `ipAddressListId` when creating a new rule, but `ipAddressList.id` when retrieving existing rules.

**Comment by wninobla** [comment]
OK, cool.  I set a different case with the debug dump for you to review.  Just make sure it isn't something I'm doing that's dumb as that is totally possible. =)

**Comment by tintoy** [comment]
Nah, you were right it was a bug - see the notes for #42 :)

**Comment by wninobla** [comment]
OK cool.  I'll try it later on tonight and let you know if it behaves now or not.  Thanks for the quick fix!

**Comment by tintoy** [comment]
Thanks heaps for taking the time to do so :)

**Comment by wninobla** [comment]
Let me know when the release is formally compiled else I guess I can compile this manually.  I'd just rather have an actual release. =)

**Comment by tintoy** [comment]
Sure - later this afternoon:)

**Comment by tintoy** [comment]
Here's [v1.1.1](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases/tag/v1.1.1) - have fun :)
