### ISSUE TITLE
Order of child address or port lists is not preserved

### ISSUE THREAD

**Issue by tintoy** [DimensionDataResearch/terraform-provider-ddcloud#44]
Child lists is being modelled as a List, but should be modelled as a Set (since CloudControl's ordering of these is non-deterministic).

**Comment by tintoy** [comment]
@wninobla fixed :)

**Comment by wninobla** [comment]
OK cool - I'll test it out after I handle me some Ming. =)


Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data
________________________________

**Comment by tintoy** [comment]
Made you a contributor BTW :)

On 2 Nov 2016, at 7:01 AM, wninobla <notifications@github.com<mailto:notifications@github.com>> wrote:

OK cool - I'll test it out after I handle me some Ming. =)


Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data
________________________________

**Comment by wninobla** [comment]
Saw that - thanks!

BTW, the thread with Ming you will want to look at as I think there is a bug with the Windows port of Terraform.  It won't pull the os_image_id or os_image_name correctly as it errors out.  He'll upload the log file for the debug in a sec.

Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data
