### ISSUE TITLE
Enable specifying of custom URL for CloudControl API end point

### ISSUE THREAD

**Issue by tintoy** [DimensionDataResearch/terraform-provider-ddcloud#48]
The provider should allow the full base URL to be specified:

```terraform
provider "ddcloud" {
  custom_endpoint = "https://foo.bar.com/baz"

  # ...
}
```

This would use `https://foo.bar.com/baz` as the base URI for the CloudControl API (rather than the usual `https://api-{region}.dimensiondata.com`).

We will probably need to a new function to the CloudControl API client to create a client using a custom base URL instead of a region name. This is tracked by [go-dd-cloud-compute #8](https://github.com/DimensionDataResearch/go-dd-cloud-compute/issues/8).

**Comment by wninobla** [comment]
Is this to support a private/hosted MCP?  I was thinking about that though I was working on base configurations first.  If it is we definitely will want that especially if we start hosting API versions that are not of our global regions.

Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data

**Comment by tintoy** [comment]
Yep, that was my thinking :)

On 16 Nov 2016, at 2:20 AM, wninobla <notifications@github.com<mailto:notifications@github.com>> wrote:

Is this to support a private/hosted MCP? I was thinking about that though I was working on base configurations first. If it is we definitely will want that especially if we start hosting API versions that are not of our global regions.

Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data
