### ISSUE TITLE
Address lists should be able to take a list of addresses

### ISSUE THREAD

**Issue by tintoy** [DimensionDataResearch/terraform-provider-ddcloud#49]
Currently, the syntax supported by the `ddcloud_address_list` resource doesn't support being passed a list of IP addresses. Just add a list-type property of addresses (as strings).

**Comment by wninobla** [comment]
?Nice - I'll give that a try as I've been inactive since GoCD has been giving me fits... =)

Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data

**Comment by tintoy** [comment]
Thanks!

**Comment by tintoy** [comment]
[Example](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/blob/development/v1.0/docs/resource_types/address_list.md#simple).
