### ISSUE TITLE
Create async operation lock

### ISSUE THREAD

**Issue by tintoy** [DimensionDataResearch/terraform-provider-ddcloud#61]
It seems that CloudControl frequently returns `UNEXPECTED_ERROR` when 2 asynchronous operations (such as create network domain or deploy VLAN) are initiated simultaneously.

Let's create an asynchronous operation lock that ensures only one asynchronous operation is initiated at a time.

- [x] Implement lock
- [x] Create network domain
- [x] Deploy VLAN

**Comment by mingsheng36** [comment]
Great! But dont know why they're calling it async when it is actually acting more like sync?

**Comment by tintoy** [comment]
Call to deploy returns immediately. You have to keep getting the deployed entity's state until it says the work is complete. So initial call is synchronous but overall the operation is asynchronous.

**Comment by tintoy** [comment]
Now that this has been implemented, we no longer see `UNEXPECTED_ERROR` from the API.

Now we just have to deal with `RESOURCE_BUSY`, which is tracked by #11.
