### ISSUE TITLE
When "dns_primary" && "dns_secondary" not specified, ddcloud_server cannot not be deployed

### ISSUE THREAD

**Issue by mingsheng36** [DimensionDataResearch/terraform-provider-ddcloud#62]
server.tf:
```
resource "ddcloud_server" "Test_Server_1" {
  networkdomain = "${ddcloud_networkdomain.nd_1.id}"
  name = "Test Server 1"
  description = "Test Server 1 created using Terraform"
  admin_password = "secret"
  os_image_name = "CentOS 7 64-bit 2 CPU"
  memory_gb = 1
  cpu_count = 1
  cores_per_cpu = 1
  cpu_speed = "Standard"
  primary_adapter_ipv4 = "10.0.2.100"
  primary_adapter_type = "VMXNET3"
  dns_primary = "8.8.8.8" # cannot be deployed when not specified
  dns_secondary = "8.8.4.4" # cannot be deployed when not specified
  auto_start = "FALSE"
  disk {
    scsi_unit_id = 0
    size_gb = 10
    speed = "STANDARD"
  }
}
```
Error Message as follow:
```
* ddcloud_server.Test_Server_1: Request to deploy server 'Test Server 1' failed with 
status code 400 (INVALID_INPUT_DATA): primaryDns  is not valid IPv4 address.
```
```
* ddcloud_server.Test_Server_1: Request to deploy server 'Test Server 1' failed with status
code 400 (INVALID_INPUT_DATA): secondaryDns  is not valid IPv4 address.
```

Version:
terraform --> v0.7.12
provider --> v1.1.8

OS: Windows 10, 64-bit

**Comment by tintoy** [comment]
Hmm - I could either make those mandatory or just make the default Google's DNS (`8.8.8.8`, `8.8.4.4`). Do you have a preference?

**Comment by tintoy** [comment]
Fixed. Will be available in v1.1.9.

**Comment by mingsheng36** [comment]
Can I suggest to leave it empty instead of specifying Google's DNS?

~~I think~~ When Primary and Secondary DNS are not specified, CloudControl will default them to use MCP's Cloud DNS resolver. (Tested)

[https://docs.mcp-services.net/display/CCD/Cloud+DNS+Resolvers](url) for different regions.

**Comment by tintoy** [comment]
Wasn't it complaining about them not being supplied?

**Comment by mingsheng36** [comment]
From CloudControl API point of view, if you do not declare primary_dns or secondary_dns, it will still allow you to deploy the server using its own default DNS for each region.

From dd-cloud-compute-terraform, you have to declare the primary_dns and secondary_dns no matter what. (Even if you leave it as blank or did not specify) 

e.g. Server will not be able to deploy with the codes below, it will prompt you to specify primary_dns and secondary_dns
```
resource "ddcloud_server" "Test_Server_1" {
  networkdomain = "${ddcloud_networkdomain.nd_1.id}"
  name = "Test Server 1"
  description = "Test Server 1 created using Terraform"
  admin_password = "Cloud@123"
  os_image_name = "Redhat 7 64-bit 2 CPU"
  memory_gb = 1
  cpu_count = 1
  cores_per_cpu = 1
  cpu_speed = "HIGHPERFORMANCE"
  primary_adapter_ipv4 = "10.0.2.100"
  primary_adapter_type = "VMXNET3"
// dns_primary = "8.8.8.8" 
// dns_secondary = "8.8.4.4"
  auto_start = "TRUE"
  disk {
    scsi_unit_id = 0
    size_gb = 21
    speed = "HIGHPERFORMANCE"
  }
}
```

**Comment by tintoy** [comment]
Ok - we'll leave the field out entirely; CloudControl API docs say it should be optional. So yes it'll now use the CloudControl defaults if you don't specify one.

**Comment by tintoy** [comment]
Yes - have a look at the change I just made - we now omit those fields from the JSON if they are empty (which makes all the difference).

**Comment by mingsheng36** [comment]
Looks good to me

**Comment by mingsheng36** [comment]
One last thing before I close this issue. Is it possible to remove the "force new" from primary & secondary dns? Reason is because these are configurable from the OS and does not make sense to re-deploy the VM because of update on the DNS entry? If there are updates to the primary & secondary DNS I think a prompt or reminder for them to change at OS will be good enough.

Also if the below validation could be added during "plan" it would be great!
- secondaryDns should not be provided if primaryDns has not been provided.

Any view on this @tintoy ?

**Comment by wninobla** [comment]
Not sure if I'm reading this right but changing the DNS values should not force a new deploy of new systems.  If I recall it wasn't that behavior in my deployments.  As for the the DNS fields in general, due to howTerraform is scoped out I would say that a change on one invites changes on both since this is a configuration toool for deployments and not one for OS changes.  That should be done via post config tools like Ansible.

Just my two cents worth.

**Comment by mingsheng36** [comment]
Hey Will, just tested it and it actually re-deployed my VM due to updates to the primary / secondary DNS. Went to look at the code and saw (force new) was "true". Was wondering what might be the reason @tintoy included that actually. 

With regards to the new changes, here are the main ones that I could think of.
-Feature,  Add the ability to manage default firewall rules
- Enhancement, Primary_adapter_vlan and primary_adapter_ipv4 are now mutually exclusive
- Enhancement, Deploying Network Domains and VLANs will automatically deploy sequentially if dependencies are not specified (by using request retries if "RESOURCE BUSY")
- Bug, Primary & Secondary DNS will use region's default Cloud DNS resolvers if unspecified (previously had to explicitly specify if not it will not pass the validation of the provider)
- Bug, Fixed a bug where using "customer_image_id" to specify image will cause terraform to crash

I think more detailed information will be at the "[release](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases)" page

**Comment by wninobla** [comment]
OK cool.  Those were the ones I expected actually so I thin kI am up to speed on these all.  I'm going to craft a few scenarios in GoCD to do some CI on the features.  If there are others we want to test let me know.  But, my aim is to do the following:


1)  Run a staging test or 'terraform plan' to gather results and spit it out to an out file

2) Run a production test or 'terraform apply 'plan.out' results file to deploy new infrastructure while fanning it out to:

        ?- Different Geos for deployment

        - Running against Windows and Linux 64-bit providers manually setting version type (basically pulling a version so we can test it out)

        - Running terraform manually setting version type (basically pulling a version so we can test it out)

3)  Running a quick test (In progress) to ensure environment was built correctly; Email notification is planned for now to flag completion/fail status of the job once its ready

4) Tearing down the environments


Anyhow, if there is stuff you think is useful let me know.  Else, I am wrapping this up just as a quick test sine we're neck deep in the code both you and I.  =)?


________________________________

**Comment by mingsheng36** [comment]
Some add-ons from me with regards to the number 2) production test.

- Different Geos for deployment (across regions)
**- Different Datacenters for deployment (within same regions)
- Different Network Domains for deployment (within same datacenter)**
- Running against Windows 32 & 64-bit and Linux 64-bit providers manually setting version type (basically pulling a version so we can test it out)
- Running terraform manually setting version type (basically pulling a version so we can test it out)

Understand that if it works on different Geos, it logically should work on different Datacenters within same region and also different Network Domains within same Datacenter. But I am just trying to be safe here as from most of the deployments I have encounter mostly falls into those two. @wninobla any views?

**Comment by wninobla** [comment]
Yeah no the multi data center in same geo as well as regional deployments are on the plan as the scripts are written that way to accept variables to segregate the builds.  On 32-bit it may be hard to do that buy I can more than certainly try to maintain that version on say a Windows 2008 non-R2 release.

Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data

________________________________________

**Comment by mingsheng36** [comment]
Understand that, but some issues come by when you run them altogether (e.g. sequence deployment) or separately. Few example might be "time-out" issue, "retry" issue and simultaneous deployment issue like we had before #57 #59 which we then know we needed #61

**Comment by mingsheng36** [comment]
Ah. Ignore my previous post. With regards to 32-bit, I am perfectly fine with taking that out. Cheers!

**Comment by wninobla** [comment]
?Yeah - I set depends_on on teh resources as I know for instance the VLAN creation is a process where it can only create a singular VLAN at a time due in part to how it has to run on the backend and apply amongst other things the VPN policy by applying the newly created networks to the user profiles for a user account.  Still, its a good point to oversee.


Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data
________________________________

**Comment by wninobla** [comment]
?OK so noted though if we're running a broader set of OS versions in our cloud I may as well maintain it until we stop developing the 32-bit iteration.  You can take the MacOS version on if you like... =)


Regards,

William Ninobla
Sr. Solutions Architect
Cloud Business Unit
Dimension Data
________________________________

**Comment by mingsheng36** [comment]
Sure. Till I invest in a MacBook. Alright, we shall not spam our unrelated posts in this issue and probably should delete our comments. I am going to start with mine.

**Comment by tintoy** [comment]
Hmm, I think this might be due to a mismatch in expectations. What `ForceNew` implies is that you can't change a value after the resource has been created. In this case, you can't ask CloudControl to change the DNS IPs because that only works during deployment.

So how do we communicate to the user that `primary_dns` and `secondary_dns` cannot be modified (via Terraform at least) after deployment?

Or to put it another way, let's turn it around - why do you want to modify `primary_dns` and / or `secondary_dns` for a `ddcloud_server` that has already been deployed?

**Comment by tintoy** [comment]
BTW, @mingsheng36, cross-property validation cannot be done during the `plan` stage. Only during `apply` (Terraform limitation unfortunately).

**Comment by wninobla** [comment]
Actually that makes sense now that I think about it as the DNS values are considered database values from the cloud UI standpoint.  It just so happens that it will use the guest OS customization to deploy that initially.  Changes to the values because of that will then precipitate a new server build.  TheIpv4 address may be different as it uses the VM tools to change stuff but its not at all consistent.  So, I’d tend to agree with Adam here on the behavior.

**Comment by tintoy** [comment]
But I believe we _could_ validate those 2 properties against each other if we moved them down a level:

```hcl
resource "ddcloud_server" "xxx" {
  name = "yyy"
  # ...
  dns {
    primary   = "8.8.8.8"
    secondary = "8.8.4.4"
  }
}
```

Then we can have an overall validator for the `dns` property that checks values for `primary` and secondary`.

**Comment by tintoy** [comment]
> But I believe we _could_ validate those 2 properties against each other if we moved them down a level

Actually, no, it looks like we can't (just checked the Terraform source code, it you can't have `plan`-time validation for Map-type properties. Ugh. Sorry, this is in the too-hard basket for now. We'll have to stick with doing any and all cross-property validation at `apply`-time.

Having said that, I could make the entire `dns` property optional but then make both its `primary` and its `secondary` properties required. That'd accomplish what you're after - "either both or neither, but not just one". Unless you expect them to be able to supply `primary` but not `secondary`? In which case it can't be done until we `apply` :-/

**Comment by mingsheng36** [comment]
I would agree with @tintoy and choose to go with both or nothing. 

Single Primary DNS i think is quite uncommon to me. But @wninobla might have some opinion on that? :)

**Comment by tintoy** [comment]
I'm closing this issue, but we can create a new issue for the enhancement to split up the DNS fields so they're either both required or neither.
