### ISSUE TITLE
Unable to Deploy Server using Client Images

### ISSUE THREAD

**Issue by mingsheng36** [DimensionDataResearch/terraform-provider-ddcloud#64]
Suggestion - To standardize to use only 'os_image_id' OR 'os_image_name' for any server deployment (default images or client images) and remove 'customer_image_id' and 'customer_image_name' from schema as they are exactly the same thing

P.S. I was a little confused by the options for images the first time when I encountered this.
```
  # Default Image, only customer_image_id cannot deploy successfully, the rest are ok
  //  os_image_id = "048f4ad9-256f-4bbe-8346-9dbaa21b332f"
  //  os_image_name = "RedHat 7 64-bit 2 CPU"
  customer_image_id = "048f4ad9-256f-4bbe-8346-9dbaa21b332f" # terraform crashed
  //  customer_image_name = "RedHat 7 64-bit 2 CPU"

  # Client Image - Redhat, according to CloudControl v2.3 APIs, All Linux Client images should not require "admin_password"
  //  os_image_id = "dde11c6a-588c-44fb-84d9-64a1d94c8dcc" # terraform crashed
  //  os_image_name = "Redhat-Client-Image" # terraform crashed
  //  customer_image_id = "dde11c6a-588c-44fb-84d9-64a1d94c8dcc" # terraform crashed
  //  customer_image_name = "Redhat-Client-Image" # terraform crashed
  
# Client Image - Windows, according to CloudControl v2.3 APIs, All Windows 2003 Client images should not require "administrator_password"  (excluding Widows 2008 & 2012 whch still requires admin_password)
  //  os_image_id = "ec356879-6187-4686-84c7-aaaf7a124c60" # terraform crashed
  //  os_image_name = "Windows-Client-Image" # terraform crashed
  //  customer_image_id = "ec356879-6187-4686-84c7-aaaf7a124c60" # terraform crashed
  //  customer_image_name = "Windows-Client-Image" # terraform crashed
```

**Comment by tintoy** [comment]
Customer and OS images are not the same though. Certainly not according to the CloudControl API.

**Comment by tintoy** [comment]
Customer and OS images are separate in CloudControl but you're right that I could merge the 2 Id properties. But if we look them up by name then we MUST know if they are OS or customer images (currently the CloudControl API docs refer to customer and OS images but I've heard them called default and customer before, too).

Can you post details of the crash? It certainly should work but I had to refactor the image management a while back so perhaps something is broken now.

**Comment by tintoy** [comment]
Actually @mingsheng36 I've looked at the CloudControl documentation and, for better or worse, the `os_image_id` and `customer_image_id` properties have to stay.

The reason that customer and OS images have to be treated differently?

Get OS image by Id: `GET https://<Cloud API URL>/caas/2.3/{org-id}/image/osImage/{image-id}`
Get customer image by Id: `GET https://<Cloud API URL>/caas/2.3/{org- id}/image/customerImage/{image-id}`

So we can't have a single API call to fetch OS _or_ customer image based on Id (I don't even see any guarantees in the documentation that Ids have to be unique between customer and OS images).

I'm sorry about that - I agree the terminology is confusing, but it _is_ the official CloudControl terminology. Right from the start I've maintained the design philosophy that the Terraform provider must not invent new terms or abstract away CloudControl concepts. It uses the same terminology as the CloudControl API because that's what people who use CloudControl are going to encounter - we're not trying to produce a "better CloudControl" but merely expose what is already there.

I'll see if I can improve the documentation though - if you have any suggestions there I'm happy to take them onboard.

**Comment by tintoy** [comment]
But like I said - post the crash log and I'll see to it that the crash is fixed at least :)

**Comment by tintoy** [comment]
Ugh! Just had a look at the code, and there's definitely a bug there (looks like it broke at some point when merging changes from an upstream branch).

See commit 2b92dc3.

**Comment by tintoy** [comment]
That code was a mess! A few more fixes in 	commit c577b80. That should do the trick now.

**Comment by tintoy** [comment]
Nevertheless, send through your crash details so I can make sure I've fixed the problems you were seeing.

**Comment by mingsheng36** [comment]
Totally agree with that they are two different things from CloudControl Client Images (client imported images) and Default Images (CloudControl provided images) perspective which will only come into concern when we are doing Client/Customer Images Management (e.g. CRUD Client Images) which cannot be performed on Default Images. In that scenario, your point is totally correct that we have to separate them, using the CloudControl API url that you have provided.

What I am referring to when I was raising this issue is during **Server Deployment**, both should be categorized under "os_images". Why?

If you could take a look at CloudControl API v2.3 page 236 (Server Deployment APIs), there is only one field called "image id" (for Default and Client Images, hence it indirectly guarantees that they are unqiue IDs, infact, UUID) and if you were to follow their principles then logically there should be only one image_id or image_name field (for readability) and at the backend should be able to perform the validations below.

- All Default Images and Windows Client Images (2008 & 2012) should require "admin_password"
- All Linux Client Images should not require "admin_password"
- All Windows 2003 Client Images should not require "admin_password"  (excluding Windows 2008 & 2012)

_Can you post details of the crash? It certainly should work but I had to refactor the image management a while back so perhaps something is broken now._

But nonetheless, if you insist that separating them even for server deployments, I am ok with that and would gladly provide to crash logs for you to fix it in a moment. Just got home from dinner. :)

**Comment by mingsheng36** [comment]
@tintoy Do you mind providing a release after this fix, together with the merged server with server_nic feature? I think it would be an appropriate checkpoint as tomorrow I will be starting work and might not be able to spend much time on terraform (even at night) :(

**Comment by tintoy** [comment]
Unfortunately, that single Id field isn't all that's required - we have to retrieve the image details so we can apply customisation of the deployServer payload to disks, memory, and CPU, etc. something we can't do without knowing the image type.

As for not requiring an admin password, that may be a little complex for this release (we'd need a programmatic way to determine if it is required for a given image). I'll have a think about it and get back to you.

Thanks for all your help BTW, I do appreciate it :)

PS. Will do a release this afternoon but It won't include merging of NICs. That's in the next version as it's a big change and will need a lot of testing...

**Comment by tintoy** [comment]
I'll have a think about how the image stuff could be improved for v1.2 (due in 2-3 weeks) - no promises but I'll do my best :)

**Comment by tintoy** [comment]
Ok - I'm going to build a release shortly. Not everything is in it because there are a lot of different things we've been talking about (and most of these GitHub issues actually refer to multiple issues) and I'm having a little trouble keeping track of it all :)

I'll spend some time reorganising the issues later this week but for now, you can check the new release notes to see what's in there.

**Comment by mingsheng36** [comment]
I see. Firstly, apologize for not understanding the complexity change of the design and the amount of work needed to simplify this one. I can certainly understand if this is going to be at the backlog or least priority as we still could have all the options out there (os, customer images) to deploy servers. 👍 

Regarding merging of NICs v1.2, I totally understand the amount of work needed to do the testings, I will try to download from branch and try to compile it myself and give it a GO. :)
(Any advice will be of great help!)
 
Really thanks for the great support and fixes that you have been providing, @tintoy ! 👍

**Comment by tintoy** [comment]
Ok - try [v1.1.9](https://github.com/DimensionDataResearch/dd-cloud-compute-terraform/releases/tag/v1.1.9). I've had to push the disk speed changes back to v1.2 (sorry about that but it's getting hard to maintain 2 branches - every change I have to make right now has to be applied against 2 increasingly-different codebases). But the rest of the things we discussed are in there (see the release notes for details).

**Comment by mingsheng36** [comment]
No worries! :100:

**Comment by mingsheng36** [comment]
#Okay, just tested using the Client Images to deploy servers. Everything is ok but just one thing: admin_password needs to be optional;
- When I specify using Client Image to deploy (which by default should not need password), provider prompt me to specify an "admin_password".
- But when I specify the admin_password (some random words in order to pass the provider validation), CloudControl validation fails.

So what I did was to actually specify it but leave it as blank (e.g. admin_password = "") and then it will pass both validation and deploy the server successfully. 

Nonetheless this discussion shall be moved to #65
