### ISSUE TITLE
 additional_network_adapter always forces new resource

### ISSUE THREAD

**Issue by mgoldsmi** [DimensionDataResearch/terraform-provider-ddcloud#74]
After successfully creating a service resource, when I re-run the plan I get the output below. It would appear that the recent implementation of the additional_network_adapter is causing servers to always be rebuilt.

$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be persisted to local or remote state storage.

ddcloud_networkdomain.customer-domain: Refreshing state... (ID: 1ab7fced-bb59-4030-a2cd-bccc11e4353d)
data.ddcloud_networkdomain.shared-services-domain: Refreshing state...
data.ddcloud_vlan.shared-services-data-vlan: Refreshing state...
ddcloud_vlan.customer-data-vlan: Refreshing state... (ID: be89b092-1512-4d72-8715-7c9f36fef90a)
ddcloud_address_list.shared-service-zone-ipv6: Refreshing state... (ID: d08d55ea-e617-4ba7-a41d-bb0093a74393)
ddcloud_server.vpn-server: Refreshing state... (ID: 27764312-de95-4d1c-91ec-d8664d5f9f89)
ddcloud_firewall_rule.shared-service-ipv6-in: Refreshing state... (ID: 7d7be4f8-9634-490b-b54f-dbcfb6adb3a6)

<snip>

-/+ ddcloud_server.vpn-server
    additional_network_adapter.#:   "" => "<computed>" (forces new resource)

$ terraform --version
Terraform v0.7.13

$ terraform-provider-ddcloud --version
terraform-provider-ddcloud v1.2.0-alpha3 (7a1232cb1a389036c8bc9ffe76244cd3d048124c)

**Comment by tintoy** [comment]
Hi :)

This should be fixed in beta1 (which is out now). Sorry about that.

**Comment by tintoy** [comment]
Hi. I've verified this in beta1. Feel free to reopen if that doesn't fix it for you.
