### ISSUE TITLE
Terraform shutting down ddcloud_server after 2nd "apply" even without changes

### ISSUE THREAD

**Issue by mingsheng36** [DimensionDataResearch/terraform-provider-ddcloud#78]
1. Deployed a first server with "auto_run=TRUE" using _apply_
2. Once successfully deployed, added another ddcloud_server
3. Run _apply_ again and it automatically shuts down the first server although it did not have any changes/updates.

**Comment by tintoy** [comment]
Could you attach a log file?

**Comment by mingsheng36** [comment]
Mistakes from my side :) Sorry for the trouble

**Comment by tintoy** [comment]
No trouble at all ;)
